---
- name: monitor linux server
  hosts: "{{ target_host }}"
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  tasks:
    - name: run command
      shell: 
        cmd: "{{ run_command }}"
      delegate_to: "{{ target_host }}"
      register: monitor_result
      
    - name: save top output 
      copy:
       content: "{{ monitor_result.stdout }}"
       dest: "/opt/{{ target_host }}-{{ date }}.csv"
      delegate_to: localhost
      
    - name: sent mail
      mail:
        host: 10.5.0.99
        subject: Monitoring report
        body: "Proof for {{ trigger }} on {{ target_host }}" 
        from: do-not-reply@kbzgateway.com 
        to: khinpyaephyo.san@kbzgateway.com
        #it-vm-opensys@kbzgateway.com 
        #cc: aung.moe@kbzgateway.com 
        attach: "/opt/{{ target_host }}-{{ date }}.csv"
      delegate_to: localhost
...      
